name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AaryanGole26 # Your GitHub username
          svg_out_path: github-contribution-grid-snake.svg
      
      # Debugging: Check if the SVG file was generated correctly
      - run: ls -l

      # Commit and push the SVG file to the output branch
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # This is where the SVG will be stored
          build_dir: .  # The root directory since we are pushing directly
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
