name: Generate Datas

on:
  schedule: 
    - cron: "* */12 * * *"  # This cron runs the job every 12 hours
  workflow_dispatch:  

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: AaryanGole26
          svg_out_path: dist/github-contribution-grid-snake.svg 
      - run: ls -l dist  
      - uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  
          build_dir: dist  
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set output to confirm the completion
        run: echo "BUILD_STATUS=success" >> $GITHUB_ENV 
